#!/usr/bin/env python
# -*- coding: utf-8 -*-

import logging
import numpy as np
from utilities import generate_data_arr_for_saving


def save_data(sensor,
              time_arr_filter,
              time_arr,
              lkf_num_history_manager,
              lkf_exp_approx_history_manager,
              extended_kf_history_manager,
              extended_kf_history_manager_lin,
              unscented_kf_history_manager,
              steady_state_history_manager,
              zs_filter_freq,
              error_jy_LKF,
              error_jz_LKF,
              error_q_LKF,
              error_p_LKF,
              error_waveform_LKF,
              error_jy_EKF,
              error_jz_EKF,
              error_q_EKF,
              error_p_EKF,
              error_waveform_EKF,
              zs_sigma,
              args,
              file_basename,
              config):
    # PLOTS=========================================================
    logger = logging.getLogger(__name__)
    logger.info('Preparing data for saving.')
    # Get history data from sensor state class and separate into blocks using "zip".
    j_y_full_history, j_z_full_history, q_q_full_history, q_p_full_history = zip(*sensor.state_vec_full_history)
    waveform = sensor.waveform_history
    print(len(zs_sigma), len(zs_filter_freq))

    labels_filter = ['time_arr_filter',
                     'jy_lin', 'jy_lin_approx', 'jy_ext', 'jy_ext_lin', 'jy_unsc', 'jy_err_lin_cov', 'jy_err_lin_approx_cov', 'jy_err_ext_cov', 'jy_err_ext_lin_cov', 'jy_err_unsc_cov', 'jy_err_lin', 'jy_err_ext', 'jy_steady_err',
                     'z',
                     'jz_lin', 'jz_lin_approx', 'jz_ext', 'jz_ext_lin', 'jz_unsc', 'jz_err_lin_cov', 'jz_err_lin_approx_cov', 'jz_err_ext_cov', 'jz_err_unsc_cov', 'jz_err_ext_lin_cov', 'jz_err_lin', 'jz_err_ext', 'jz_steady_err',
                     'q_lin', 'q_lin_approx', 'q_ext', 'q_ext_lin', 'q_unsc', 'q_err_lin_cov', 'q_err_lin_approx_cov', 'q_err_ext_cov', 'q_err_ext_lin_cov', 'q_err_unsc_cov', 'q_err_lin',
                     'q_err_ext', 'q_steady_err',
                     'p_lin', 'p_lin_approx', 'p_ext', 'p_ext_lin', 'p_unsc', 'p_err_lin_cov', 'p_err_lin_approx_cov', 'p_err_ext_cov', 'p_err_ext_lin_cov', 'p_err_unsc_cov', 'p_err_lin', 'p_err_ext', 'p_steady_err',
                     'waveform_est_LKF', 'waveform_est_EKF', 'waveform_est_LKF_err', 'waveform_est_EKF_err',
                     'waveform_real_LKF_err', 'waveform_real_EKF_err', 'waveform_ss_error', 'z/sigma']
    labels_simulation = ['time_arr_simulation', 'jy_real', 'jz_real', 'q_real', 'p_real', 'waveform']

    if np.any([args[0].lkf_num, args[0].lkf_exp, args[0].lkf_expint, args[0].ekf, args[0].ukf]):
        logger.info("Saving simulation data to csv file")
        all_data_filter = generate_data_arr_for_saving(np.array([time_arr_filter,
                                                                lkf_num_history_manager.jys,
                                                                 lkf_exp_approx_history_manager.jys,
                                                                extended_kf_history_manager.jys,
                                                                 extended_kf_history_manager_lin.jys,
                                                                unscented_kf_history_manager.jys,
                                                                 lkf_num_history_manager.jys_err_post,
                                                                 lkf_exp_approx_history_manager.jys_err_post,
                                                                 extended_kf_history_manager.jys_err_post,
                                                                 extended_kf_history_manager_lin.jys_err_post,
                                                                 unscented_kf_history_manager.jys_err_post,
                                                                 error_jy_LKF,
                                                                 error_jy_EKF,
                                                                 steady_state_history_manager.steady_posts_jy,
                                                                 zs_filter_freq,
                                                                 lkf_num_history_manager.jzs,
                                                                 lkf_exp_approx_history_manager.jzs,
                                                                 extended_kf_history_manager.jzs,
                                                                 extended_kf_history_manager_lin.jzs,
                                                                 unscented_kf_history_manager.jzs,
                                                                 lkf_num_history_manager.jzs_err_post,
                                                                 lkf_exp_approx_history_manager.jzs_err_post,
                                                                 extended_kf_history_manager.jzs_err_post,
                                                                 extended_kf_history_manager_lin.jzs_err_post,
                                                                 unscented_kf_history_manager.jzs_err_post,
                                                                 error_jz_LKF,
                                                                 error_jz_EKF,
                                                                 steady_state_history_manager.steady_posts_jz,
                                                                 lkf_num_history_manager.qs,
                                                                 lkf_exp_approx_history_manager.qs,
                                                                 extended_kf_history_manager.qs,
                                                                 extended_kf_history_manager_lin.qs,
                                                                 unscented_kf_history_manager.qs,
                                                                 lkf_num_history_manager.qs_err_post,
                                                                 lkf_exp_approx_history_manager.qs_err_post,
                                                                 extended_kf_history_manager.qs_err_post,
                                                                 extended_kf_history_manager_lin.qs_err_post,
                                                                 unscented_kf_history_manager.qs_err_post,
                                                                 error_q_LKF,
                                                                 error_q_EKF,
                                                                 steady_state_history_manager.steady_posts_q,
                                                                 lkf_num_history_manager.ps,
                                                                 lkf_exp_approx_history_manager.ps_err_post,
                                                                 lkf_exp_approx_history_manager.ps,
                                                                 extended_kf_history_manager.ps,
                                                                 extended_kf_history_manager_lin.ps,
                                                                 unscented_kf_history_manager.ps,
                                                                 lkf_num_history_manager.ps_err_post,
                                                                 extended_kf_history_manager.ps_err_post,
                                                                 extended_kf_history_manager_lin.ps_err_post,
                                                                 unscented_kf_history_manager.ps_err_post,
                                                                 error_p_LKF,
                                                                 error_p_EKF,
                                                                 steady_state_history_manager.steady_posts_p,
                                                                 lkf_num_history_manager.waveform_est,
                                                                 extended_kf_history_manager.waveform_est,
                                                                 lkf_num_history_manager.waveform_est_err,
                                                                 extended_kf_history_manager.waveform_est_err,
                                                                 error_waveform_LKF,
                                                                 error_waveform_EKF,
                                                                 steady_state_history_manager.steady_waveform_err,
                                                                 zs_sigma
                                                                 ]),
                                                                    labels=labels_filter,
                                                                    bools=[True,
                                                                        args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           True,
                                                                           True,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           True,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           True,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].ekf,
                                                                           args[0].ukf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           True,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           args[0].lkf_num,
                                                                           args[0].ekf,
                                                                           True,
                                                                           True
                                                                           ])
        all_data_simulation = generate_data_arr_for_saving(np.array([time_arr,
                                                                     j_y_full_history,
                                                                     j_z_full_history,
                                                                     q_q_full_history,
                                                                     q_p_full_history,
                                                                     waveform]),
                                                       labels=['time',
                                                               'Jy',
                                                               'Jz',
                                                               'q',
                                                               'p',
                                                               'waveform'],
                                                       bools=[True,
                                                              True,
                                                              True,
                                                              True,
                                                              True,
                                                              True])
        all_data_filter.to_csv(file_basename + '_kf_gp_%r_wp_%r.csv'% (config.coupling['g_p'], config.coupling['omega_p']), sep='\t', na_rep='Unknown')
        all_data_simulation.to_csv(file_basename + '_sim_gp_%r_wp_%r.csv' % (config.coupling['g_p'], config.coupling['omega_p']), sep='\t', na_rep='Unknown')
    return
